### ISSUE TITLE
Method [throwValidationException] does not exist.

### ISSUE THREAD

**Issue by udemethegrtman** [RachidLaasri/LaravelInstaller#117]
I tried using the laravel installer package after testing the installer with all my details to install a new app i got this error.

`Method [throwValidationException] does not exist.`

LARAVEL VERSION: 5.5.13

**Comment by adamthomason** [comment]
I also get this error - I'd really like to use this package but this is a blocker really

**Comment by TechTailor** [comment]
I encountered the same issue and after looking into the code and retrying several times, I identified the cause and was able to complete the process without any errors.

All you have to do is look into the config/installer.php file. Which stores all the validation rules for the forms.

The conditions set make it "required" for almost all the data in the .env form to not be "null" apart from the pusher api data. Since most people don't use redis out of the box and as such dont configure it during the setup, the form is sending empty/null which is causing the error.

SOLUTION - 

1. Either add dummy data for the redis settings, etc or
2. Remove the "required" part for all the settings your app doesn't require in the "config/installer" file.
               
Ex: This
> 'redis_hostname'        => 'required|string|max:50',
> 'redis_password'        => 'required|string|max:50',
> 'redis_port'            => 'required|numeric',

to

> 'redis_hostname'        => 'string|max:50',
> 'redis_password'        => 'string|max:50',
> 'redis_port'            => 'numeric',

Lastly, you can make the above changes and try it out in a fresh installation. If you have already attempted to use this and failed, then make sure you delete all tables in the db and the cache in storage folder before trying it out in an earlier app.

Hope this fixes your issue.

-TT

**Comment by nabeelio** [comment]
I've created a simple fix here, it shows the validation errors in the view: https://github.com/nabeelio/LaravelInstaller/commit/0a5877b5550b0f8b35ed354331f1250747c9c223

**Comment by RachidLaasri** [comment]
Fixed
