### ISSUE TITLE
Security issue

### ISSUE THREAD

**Issue by joveice** [RachidLaasri/LaravelInstaller#141]
At [line 98 in EnvironmentManager](https://github.com/RachidLaasri/LaravelInstaller/blob/master/src/Helpers/EnvironmentManager.php#L98) you have a hardcoded key. This should at least be generated at install, or you should replace value by value in the .env file instead of overwriting the whole file (leaving custom config values alone).

One way or another, the key should not be hardcoded.

**Comment by RachidLaasri** [comment]
A PR would be nice :)

**Comment by joveice** [comment]
Sure, I can do that.

**Comment by RachidLaasri** [comment]
Just double checked. There are no security issues or what so ever.

We regenerate a new key on the final step: https://github.com/RachidLaasri/LaravelInstaller/blob/master/src/Helpers/FinalInstallManager.php#L20

**Comment by joveice** [comment]
Hello, I don't know how that works. But it's still overwriting it, so everyone are still getting a hardcoded
"base64:bODi8VtmENqnjklBmNJzQcTTSC8jNjBysfnjQN59btE=" key, just try it yourself on a fresh one and you will see that everyone gets this key, AKA this is still quite the security issue.

**Comment by joveice** [comment]
The key is pulled from the newly created .env file. and as you can see here
https://github.com/RachidLaasri/LaravelInstaller/blob/master/src/Helpers/EnvironmentManager.php#L98
That's a hard coded key. So why you closed my patch I have no clue.

**Comment by RachidLaasri** [comment]
Hi,

I did try it and that's why I closed your issue.

The final page you see when the installation is done is this one https://github.com/RachidLaasri/LaravelInstaller/blob/master/src/Routes/web.php#L49 and as you can see it is calling a finish method inside the FinalController class. If you take a look at that  https://github.com/RachidLaasri/LaravelInstaller/blob/master/src/Controllers/FinalController.php you can clearly see that it is calling a runFinal on the FinalInstallManager class and that method https://github.com/RachidLaasri/LaravelInstaller/blob/master/src/Helpers/FinalInstallManager.php#L16-L24 itself is calling a private generateKey method which does the generation once the installer finished. So we actually do update it on the final step.

**Comment by joveice** [comment]
That key is not getting stored. Please download a fresh laravel and require your package and wall thru the install and you can see for yourself.

**Comment by joveice** [comment]
I just did, and I can confirm that it's the same key in the .env file as the one in the environment helper.

**Comment by RachidLaasri** [comment]
Just tried it again on a fresh Laravel install and the key gets updated on the final step.

**Comment by joveice** [comment]
Did you open the .env file and see yourself or are you trusting the output from the console? I would trust the file over the console...

**Comment by RachidLaasri** [comment]
Trust me, I did check the file itself.

**Comment by joveice** [comment]
Odd that on what ever platform I do this on I get this key in the .env file after the installer is done:
```
base64:bODi8VtmENqnjklBmNJzQcTTSC8jNjBysfnjQN59btE=
```

**Comment by RachidLaasri** [comment]
Do you have this set to true or false?

https://github.com/RachidLaasri/LaravelInstaller/blob/master/src/Config/installer.php#L21

**Comment by joveice** [comment]
It's true

**Comment by joveice** [comment]
This was fixed in #179 so it's no longer a concern.
