### ISSUE TITLE
Custom install step

### ISSUE THREAD

**Issue by vpratfr** [RachidLaasri/LaravelInstaller#29]
Hi,

Is it possible to easily add steps to the wizard? Like a form to enter the default admin credentials & such things?

**Comment by RachidLaasri** [comment]
Yes, you can add your own routes and controllers.

https://github.com/RachidLaasri/LaravelInstaller/blob/master/src/routes.php

**Comment by giwrgos88** [comment]
@RachidLaasri can I override your routes? for example on the environment to call my class instead of yours but keep the same url?

**Comment by RachidLaasri** [comment]
@giwrgos88 Can you explain more please?

**Comment by giwrgos88** [comment]
@RachidLaasri now if my project has domain localhost, that means I will have localhost/install/enviroment where on the routes the parameter enviroment will call the "EnvironmentController@environment". How I can keep the same url but instead of calling the EnvironmentController to call the InstallerController

**Comment by RachidLaasri** [comment]
Hmm, You can create your own routes and link them to your controllers.

**Comment by giwrgos88** [comment]
understood thanks

**Comment by vpratfr** [comment]
@giwrgos88 this is one of the reasons why I created https://github.com/marvinlabs/laravel-setup-wizard

@RachidLaasri maybe you find some useful ideas there to improve this package

**Comment by ridislam** [comment]
Can you write an example of how to use custom controller and route for custom steps
