### ISSUE TITLE
Unable to run migrations

### ISSUE THREAD

**Issue by Utkarsh-vishnoi** [RachidLaasri/LaravelInstaller#66]
I have installed your package with laravel 5.2.45, everything is correct except migrations. You can see the output on the below screenshot. My database connection type is `mysql` and username is `sic` but it's giving error about the username `homestead`. Also when i run my migration command from the console, it works! `||wtfmigrate` was added while i was debugging u'r package and i found the error was generated from this line.
![download](https://cloud.githubusercontent.com/assets/7036367/22398888/d2a9b0da-e5b6-11e6-9279-996dd9bad319.png)

**Comment by RachidLaasri** [comment]
Make sure your database info are correct when editing the .env file through the installer.

**Comment by Utkarsh-vishnoi** [comment]
They are correct. running the command via artisan console migrates the database but not via the installer.

**Comment by Tropicalista** [comment]
Same problem here. Have you solved?

**Comment by Phil795** [comment]
@Tropicalista 
Which version do you use?

**Comment by Tropicalista** [comment]
@Phil795  Laravel 5.4

**Comment by Phil795** [comment]
I think there is a mismatch with your configuration. 

The 'homestead' database user is the default in `www/laravel-blog/.env.sample` and `www/laravel-blog/config/database.php`

If you want use the .env configuration file make sure your credentials are set. And rename the file to `.env`

Otherwise you can use the php database config file, place your connection data and change this setting
`'default' => env('DB_CONNECTION', 'mysql'),` to `'default' => 'yourconnection'),`

**Comment by Tropicalista** [comment]
I have already made this changes. Seems a problem by running laravel embedded serve, if I run this on wamp it works great.

**Comment by Phil795** [comment]
I will test it tomorrow

**Comment by jeremykenedy** [comment]
@Utkarsh-vishnoi did you get this resolved? Is this still active?

**Comment by Utkarsh-vishnoi** [comment]
Yes got it solved. Just reinstalled everything and it started to work.
