### ISSUE TITLE
Would be great if you could add the option for the user to enter the database name.

### ISSUE THREAD

**Issue by FalconDev91** [RachidLaasri/LaravelInstaller#7]
This is from Invoice Ninja Installer
![image](https://cloud.githubusercontent.com/assets/13089930/9835485/e5da7bfe-5a0b-11e5-8411-874c268af307.png)

**Comment by lorvent** [comment]
+1

when we offer them web installer, they never touch .env or config/database.php

**Comment by RachidLaasri** [comment]
That's a good idea! 

I will see if i make something similar.

**Comment by lancepioch** [comment]
How about simply having a text box that can edit and save to the .env and put it on this page:

![image](https://cloud.githubusercontent.com/assets/1296882/9858889/3fb9840e-5af1-11e5-9f1b-40ad798f4f18.png)

**Comment by RachidLaasri** [comment]
@lancepioch Yeah, this is a tricky one because if your application needs more configurations ( not just the database info ) the user will still need to edit the `.env` file, then that feature will be useless. 

What i am thinking is adding a new page after the one you mentioned where you can see a form that is already populated with the `.env` file content and you can override the inputs values if you want to.

**Comment by azulkipli** [comment]
Good project, will wait for this feature

**Comment by RachidLaasri** [comment]
@lancepioch Did a great job on this one. It is completed now https://github.com/RachidLaasri/LaravelInstaller/commit/d6f9de354450d9c8bbb2f58f7f575fac0bb46395.
