### ISSUE TITLE
This installer gives errors on linux server mac & windows ok.

### ISSUE THREAD

**Issue by codePyx** [RachidLaasri/LaravelInstaller#85]
This package show this error(Illuminate\Support\ServiceProvider::loadRoutesFrom(): Failed opening required '/var/www/html/VRM/vendor/rachidlaasri/laravel-installer/src/Providers/../routes/web.php' (include_path='.:/usr/share/php')) mac & windows working perfect. laravel 5.4

**Comment by jeremykenedy** [comment]
You need to clear composer with 'composer dump-autoload' and possible clear any cache with `php artisan cache:clear`

**Comment by zoniko** [comment]
Same problem here!.. follow jeremykenedy's advice but still not working.
Error in Laravel 5.4 - Ubuntu 16. It works ok in homestead for mac and win10.

**Comment by jeremykenedy** [comment]
Off the top of my head I am thinking that it is that Ubuntu is very strict on capitalization and possibly a namespace being declared needs to be checkout out and adjusted to prevent errors on Ubuntu.

**Comment by aaxc** [comment]
Same issue here. The script tries to access `vendor/rachidlaasri/laravel-installer/src/routes/web.php` but it containts `vendor/rachidlaasri/laravel-installer/src/Routes/web.php` (notice the capitalization).

I made a copied Routes to routes and it all goes smoothly. 
This needs to be fixed asap, because I can't use it otherwise. It just doesn't feel right to make the user rename a directory to install my app :/

**Comment by Schottii** [comment]
Thanks @aaxc this helped me alot. I guess its not a big deal to rename Routes to routes. Don't know if it's worth the pull request.
Hopefully it gets fixed soon.

**Comment by RachidLaasri** [comment]
Fixed.
