### ISSUE TITLE
Call to undefined method [loadRoutesFrom] on laravel 5.2 linux

### ISSUE THREAD

**Issue by philippejadin** [RachidLaasri/LaravelInstaller#93]
I saw an other (closed) issue but I still get this error : "Call to undefined method [loadRoutesFrom]"

**Comment by Muntader** [comment]
hello philippejadin , its easy to solved this problem 
go to `/vendor/rachidlaasri/laravel-installer/src/Providers/LaravelInstallerServiceProvider.php
` 
& change   `$this->loadRoutesFrom(__DIR__.'/../routes/web.php');`
to `$this->loadRoutesFrom(__DIR__.'/../Routes/web.php');`

i hope Rachid change it in the update

**Comment by acbilimoria** [comment]
https://github.com/acbilimoria/LaravelInstaller/commit/349da268d4fbc9f30df09ee8507088bea4093148

**Comment by Muntader** [comment]
@acbilimoria Yes just change ` /routes/web.php `to` /Routes/web.php` because the name of /routes is  /Routes not /routes

**Comment by jeremykenedy** [comment]
@acbilimoria I like the idea of the logic to change the capital R, but I think it may not be needed and the service provider just needs to be updated like @Muntader suggested above.
Do you want to make an updated PR with just the simple namespace change rather than the logic?
Thanks for tracking the issue down everyone.

**Comment by acbilimoria** [comment]
Sure!  https://github.com/RachidLaasri/LaravelInstaller/pull/95

**Comment by RachidLaasri** [comment]
Fixed.

**Comment by Phil795** [comment]
I have the same problem. The above solution does not work because the function 'loadRoutesFrom' does not exist. A pure path adjustment won't help here
